Traceback (most recent call last):
  File ".\chap10.py", line 7, in <module>
    raise Exception("This is the error message")
Exception: This is the error message
